server:
  port: 8011

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 2
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: employee-service

logging:
  level:
    com.self.sprintboot.learning.employee: DEBUG