server:
  port: ${port:8761}

eureka:
  client:
    registry-fetch-interval-seconds: 5
    register-with-eureka: false
    service-url:
      default-zone: ${DISCOVERY_URL:http://localhost:8761/eureka/}
  instance:
    lease-renewal-interval-in-seconds: 10


spring:
  boot:
    admin:
      context-path: /admin